// @generated by scripts/fit_calcs.py; do not hand edit.
/// Minimum fitted Pt100 resistance in `ohm`.
pub const PT100_MIN_RESISTANCE_OHM: f32 = 1.852008000e+01_f32;
/// Maximum fitted Pt100 resistance in `ohm`.
pub const PT100_MAX_RESISTANCE_OHM: f32 = 3.904811250e+02_f32;
/// Resistance origin in `ohm` for the normalized inverse coordinate.
pub const PT100_RESISTANCE_ORIGIN_OHM: f32 = 2.045006025e+02_f32;
/// Scale in `1/ohm` for the normalized inverse coordinate.
pub const PT100_RESISTANCE_SCALE: f32 = 5.376907144e-03_f32;
/// Kelvin offset applied after inverse-polynomial evaluation.
pub const PT100_TEMPERATURE_ORIGIN_K: f32 = 2.731500000e+02_f32;
/// Lower-end inverse tangent in `K/ohm`.
pub const PT100_MIN_EXTRAPOLATION_SLOPE_K_PER_OHM: f32 = 2.313020083e+00_f32;
/// Upper-end inverse tangent in `K/ohm`.
pub const PT100_MAX_EXTRAPOLATION_SLOPE_K_PER_OHM: f32 = 3.416992705e+00_f32;
/// Ascending normalized-power coefficients in `degC` with shape `(degree + 1,)`.
pub const PT100_INVERSE_COEFFICIENTS_C: [f32; 11] = [
    2.788731079e+02_f32,
    5.186333618e+02_f32,
    4.325422668e+01_f32,
    6.534585953e+00_f32,
    2.467815638e+00_f32,
    4.023543358e+00_f32,
    -4.877301216e+00_f32,
    -6.034164429e+00_f32,
    8.759303093e+00_f32,
    1.838831186e+00_f32,
    -3.480179787e+00_f32,
];
