[package]
name = "deimos_shared"
version = "0.1.1"
edition = "2021"
authors = ["Deimos Controls <jlogan@deimoscontrols.com>"]
license = "0BSD OR Apache-2.0"
repository = "https://github.com/deimoscontrols/deimos"
homepage = "https://github.com/deimoscontrols/deimos"
description = "Shared packet formats and related resources for Deimos DAQ ecosystem"
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte_struct = "0.9.0"

serde = { version = "^1", features = ["derive"], optional = true }
typetag = { version = "^0.2", optional = true }

interpn = { version = "0.4.3", optional = true }
once_cell = { version = "1.20.2", optional = true }

[features]
default = ["std"]
std = ["serde", "typetag", "interpn", "once_cell"]