[package]
name = "deimos_shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte_struct = "0.9.0"

serde = { version = "^1", features = ["derive"], optional = true }
typetag = { version = "^0.2", optional = true }

interpn = { version = "0.4.3", optional = true }
once_cell = { version = "1.20.2", optional = true }

[features]
default = ["std"]
std = ["serde", "typetag", "interpn", "once_cell"]