[target.thumbv7em-none-eabihf]
runner = 'arm-none-eabi-gdb'
rustflags = [
  # LLD (shipped with the Rust toolchain) is used as the default linker
  "-C", "link-arg=-Tlink.x",
  "-C", "target-cpu=cortex-m7",
  # Use all floating-point instruction sets available with codegen,
  # full ARMv7 instruction set, and realtime profile
  "-C", "target-feature=+fp64,+vfp2,+rclass,+v7"
]

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)