name: Deploy docs

on:
  # push:
  #   branches: [main]
  workflow_dispatch:
  repository_dispatch:
    types: [deimos-docs]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out site repo
        uses: actions/checkout@v4
      - name: Check out deimos repo
        uses: actions/checkout@v4
        with:
          repository: deimoscontrols/deimos
          path: deimos
          fetch-depth: 1
          token: ${{ github.token }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Deploy site
        run: mkdocs gh-deploy
