name: Rust

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Format
      run: cargo fmt --check --verbose
    - name: Lint
      run: cargo clippy
    - name: Run tests
      run: |
        cargo test --verbose --no-default-features
        cargo test --verbose --features=tsdb
        cargo test --verbose --features=df
        cargo test --verbose --features=ser
        cargo test --verbose --features=affinity
        cargo test --verbose --features=sideloading
        cargo test --verbose --all-features
        cargo run --example ipc_plugin
        cargo run --example sideloading