name: Rust

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get latest rustc
      run: rustup update
    - name: Format
      run: cargo fmt --check
    - name: Lint
      run: cargo clippy --all-features
    - name: Check semver
      uses: obi1kenobi/cargo-semver-checks-action@v2
    - name: Run tests
      run: |
        cargo test
        cargo run --example ipc_plugin
        cargo run --example sideloading
        cargo build --example multi_daq
        cargo build --example basic